/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/floating island.glb -o src/components/Island.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import {Html, useGLTF} from '@react-three/drei'
import {currentPageAtom} from "./UI.jsx";
import {useAtom} from "jotai";
import { degToRad } from "three/src/math/MathUtils";

const OverlayItem = ({
                       className = "",
                       title,
                       description,
                       price,
                       bgColor,
                        button,
                       ...props
                     }) => {
  const [currentPage] = useAtom(currentPageAtom);
  return (
      <Html
          transform
          distanceFactor={1.2}
          center
          className={`w-100 rounded-md overflow-hidden ${
              currentPage === "store" ? "" : "opacity-0"
          } transition-opacity duration-1000 ${className}`}
          {...props}
      >
        <div className="bg-white bg-opacity-50 backdrop-blur-lg text-xs p-2 w-full">
          <h2 className="font-bold">{title}</h2>
          <p>{description}</p>
        </div>
        <button
            className={`${bgColor} hover:bg-opacity-0 transition-colors duration-500 px-4 py-2 font-bold text-white w-full text-xs`}
        >
          {button}
        </button>
      </Html>
  );
};



export function Island(props) {
  const { nodes, materials } = useGLTF('/models/floating island.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="andrewsisland_v10objcleanermaterialmergergles">
            <group name="Object_15" />
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.DoorsAndDoorframes} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.FirewoodRope} />
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Grass_base} />
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Groundrocks} />
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.House_PlasterWall} />
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.House_Wood_tiling} />
            <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.House_Wood_tiling} />
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.PipeLantern} />
            <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Platform_WoodTiling} />
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Balloon} />
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.RoofMaterial} />
            <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.RoofMaterial2} />
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.RoofTiles} />
            <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.ShedRoofTiles} />
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Shed_PlasterWall} />
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Shed_Wood_Tiling} />
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Smoke_Chimney} />
            <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.StonesChimney} />
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Test_Wood} />
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.WindowGlass} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Bottles} position={[0, 0, 0.007]} />
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.bell} />
            <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.stone_wall} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.BottomCabins} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Bottom_WoodTiling} />
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.CabinGlass} />
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Chimney_PBolts} />
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.ClothesPipeWater} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.CrateBarrel} />
            <group position={[0, 0, 0.007]}>
            <mesh name="separate_vase" geometry={nodes.separate_vase.geometry} material={materials.Bottles} />
                  <OverlayItem
                      rotation-x={degToRad(90)}
                      rotation-y={degToRad(15)}
                      position-x={-1}
                      position-z={1.1}
                      position-y={-5}
                      title={"Welcome to my portofolio!"}
                      description={"My name is Alex , and i am Computer Science student from Romania and Project Mayhem is my portofolio."}
                      bgColor={"bg-yellow-500"}
                      button={"More info"}
                      className={"transition delay-1000"}
                  />
                <OverlayItem
                    rotation-x={degToRad(90)}
                    position-x={0.6}
                    position-z={1.6}
                    position-y={-3}
                    title={"My projects"}
                    description={"I have contributed to many projects but here are those which i hold closest to my heart."}
                    button={"View projects"}
                    bgColor={"bg-red-500"}
                    className={"transition delay-1000"}
                />
                <OverlayItem
                    rotation-x={degToRad(90)}
                    position-x={-2}
                    position-z={1.6}
                    position-y={-3}
                    title={"The Socratic Exchange: A Journey into Philosophy"}
                    description={"Welcome to The Socratic Exchange, your portal to philosophical inquiry and contemplation."}
                    button={"View blog"}
                    bgColor={"bg-orange-500"}
                    className={"transition delay-1000"}
                />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/floating island.glb')
